spring:
  datasource:
    username: rhfgngczpptley
    password: 30f6fef0ee641aa654c4ee467969caceac1606436e3c24b3f714f527aa4bd11e
    url: jdbc:postgresql://ec2-54-77-120-158.eu-west-1.compute.amazonaws.com:5432/d9t59og67apj27
    driver-class-name: org.postgresql.Driver
  hikari:
    maximum-pool-size: 5
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
  sql:
    init:
      platform: postgres
      mode: always
